### ISSUE TITLE
Double click flatimge, it opens then closes immediately

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#107]
Backtrace:

thread 'main' panicked at launcher/src/frame/cover.rs:200:93:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x633e7df10c5a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h314cd50504129941
   1:     0x633e7df38233 - core::fmt::write::hc2ee7d2d213c8e87
   2:     0x633e7df0d973 - std::io::Write::write_fmt::h7394b16a4a4f3368
   3:     0x633e7df10aa2 - std::sys::backtrace::BacktraceLock::print::hf978fb87e8f10258
   4:     0x633e7df11a4c - std::panicking::default_hook::{{closure}}::h1dd794631d09a81f
   5:     0x633e7df11892 - std::panicking::default_hook::h74245ae16a8e3fed
   6:     0x633e7df12087 - std::panicking::rust_panic_with_hook::ha97360e1af624ce0
   7:     0x633e7df11ee6 - std::panicking::begin_panic_handler::{{closure}}::h45813efe693be889
   8:     0x633e7df11139 - std::sys::backtrace::__rust_end_short_backtrace::hed80b0bf9cba864a
   9:     0x633e7df11bac - rust_begin_unwind
  10:     0x633e7df36cd0 - core::panicking::panic_fmt::ha4275ca3c44593bc
  11:     0x633e7df36d5c - core::panicking::panic::hf5911a50f8ecee2d
  12:     0x633e7df36c49 - core::option::unwrap_failed::hba2259e7d0bcad62
  13:     0x633e7dde77c9 - launcher::frame::cover::new::hfdf9cc97df726dee
  14:     0x633e7ddddbd2 - launcher::Gui::redraw::hf00f7ea084ca2344
  15:     0x633e7dde0dca - launcher::main::h7ed505898c5b90e9
  16:     0x633e7ddd5b73 - std::sys::backtrace::__rust_begin_short_backtrace::hc3c9828937714a34
  17:     0x633e7dde58d9 - std::rt::lang_start::{{closure}}::hc9b9205c730a833f
  18:     0x633e7df0884e - std::rt::lang_start_internal::h2dd41d4bc5ea291e
  19:     0x633e7dde11e5 - main
  20:     0x7998b01dde08 - <unknown>
  21:     0x7998b01ddecc - __libc_start_main
  22:     0x633e7ddd21e5 - _start
  23:                0x0 - <unknown>

**Comment by ruanformigoni** [comment]
Seems like an error with the executables database, I'll dig on it further.

**Comment by malnaanah** [comment]
FlatImage does not work in version 1.4.0, i get this error.

thread 'main' panicked at launcher/src/frame/cover.rs:200:93:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ruanformigoni** [comment]
This is now fixed in `v1.4.1`, thank you @Blad3forc3 and @malnaanah for the heads up :smile:
