### ISSUE TITLE
Wine hq staging plays games that the wine staging appimage doesn't 

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#23]
Is the appimage on here for wine staging based on the wine hq staging build with wine?
I ask because I have games installed with the latest wine hq staging from the wine website that run ok from the hard drive as a normal wineprefix but when I package them into an appimage using the latest wine staging (8.4) appimage they don't run.
Also could you publish a how to build your own wine appimage for inclusion into the gameimage

**Comment by ruanformigoni** [comment]
Hi @Blad3forc3 , I'll release an `arts` package to replace `appimage` in the future. That should resolve some of these issues.

**Comment by Blad3forc3** [comment]
I've tried building as you wrote but all i'm getting is lots of errors with your recipe file.

**Comment by ruanformigoni** [comment]
It is probably with `appimage-builder` and not the recipe. Could you post the log output?

**Comment by Blad3forc3** [comment]
Traceback (most recent call last):
  File "/tmp/.mount_appimaurQ0Dy/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 40, in __main__
    raw_recipe_data = recipe_loader.load(args.recipe)
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/appimagebuilder/recipe/loader.py", line 76, in load
    return yaml.load(recipe_file, Loader=self._loader)
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/tmp/.mount_appimaurQ0Dy/usr/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./wine-staging.yml", line 27, column 66

**Comment by ruanformigoni** [comment]
The indentation in the file needs to be exact, try to download the `raw` file [here](https://raw.githubusercontent.com/ruanformigoni/wine/master/wine-staging.yml), just right click and choose `save as`.

**Comment by Blad3forc3** [comment]
OK, ive got a different error now

Traceback (most recent call last):
  File "/tmp/.mount_appimaRI2CBu/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 40, in __main__
    raw_recipe_data = recipe_loader.load(args.recipe)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/appimagebuilder/recipe/loader.py", line 76, in load
    return yaml.load(recipe_file, Loader=self._loader)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/tmp/.mount_appimaRI2CBu/usr/lib/python3.8/site-packages/appimagebuilder/recipe/loader.py", line 64, in constructor_env_variables
    raise RecipeError(
appimagebuilder.recipe.errors.RecipeError: Unable to resolve environment variable: version_wine

**Comment by ruanformigoni** [comment]
Cool, now I think you can replace `version: !ENV ${version_wine}` with something like `version: 8.4.0`.

**Comment by Blad3forc3** [comment]
I've tried replacing the version with the latest (8.5.0) and get this error

./appimage-builder.AppImage --recipe ./wine-staging.yml
INFO:main:Running main script
rm -rf AppDir appimage-builder-cache/var/cache/apt/archives/*wine* || true
mkdir AppDir && cp wrapper AppDir
cp: cannot stat 'wrapper': No such file or directory
Traceback (most recent call last):
  File "/tmp/.mount_appimazD5H12/usr/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/tmp/.mount_appimazD5H12/usr/lib/python3.8/site-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/tmp/.mount_appimazD5H12/usr/lib/python3.8/site-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/tmp/.mount_appimazD5H12/usr/lib/python3.8/site-packages/appimagebuilder/commands/run_script.py", line 82, in __call__
    raise RuntimeError("Script exited with code: %s" % _proc.returncode)
RuntimeError: Script exited with code: 1

**Comment by ruanformigoni** [comment]
Ok, you have to download the [wrapper](https://raw.githubusercontent.com/ruanformigoni/wine/master/wrapper) script, with this exact name, and save in the same folder that you saved the recipe.

**Comment by ruanformigoni** [comment]
It would be best if you could clone the entire repository, and do this within it. There are other files the script will search for.

**Comment by ruanformigoni** [comment]
Here is [wine 8.2](https://mega.nz/file/glwXjTjJ#l-OLLOalH-OBmBezIruXZLEXsZXzEt_fQ06kHlJEYa8) packed with `arts` if you want to try it out to avoid the work of building it by yourself.

**Comment by Blad3forc3** [comment]
Seems to be working now thanks RUan. After its finished can i just rename it to wine and replace the wine inside the AppDir/usr/bin inside the appimage to created?

**Comment by ruanformigoni** [comment]
Yes, that is what I do :)

**Comment by Blad3forc3** [comment]
Ok, Thanks Ruan!!! I will try the version with arts tomorrow and report back!

**Comment by ruanformigoni** [comment]
No problem, thanks for the feedback!

**Comment by ruanformigoni** [comment]
AppImage support dropped, flatimage should now offer less unexpected behaviors such as this one.
